services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - Stripe:SecretKey=
      - Stripe:PublisheableKey=
      # SECRETS FOR OTP MISSING HERE
      - ConnectionStrings:DefaultConnection=Host=db;Database=tbcpay_db;Username=postgres;Password=;
      - Jwt:Secret=
      - Google:ClientId=
      - Google:ClientSecret=
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tbcpay_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5001:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: